version: "0.2"
# Suggestions can sometimes take longer on CI machines,
# leading to inconsistent results.
suggestionsTimeout: 5000 # ms
import:
  - "../../node_modules/@cspell/dict-fonts/cspell-ext.json"
  - "../../node_modules/@cspell/dict-rust/cspell-ext.json"
  - "../../node_modules/@cspell/dict-software-terms/cspell-ext.json"
words:
  - appsscript
  - arrterian
  - atlascode
  - bunfig
  - claspignore
  - coopmoney
  - dmezhnov
  - elif
  - endfor
  - gruntfuggly
  - hverlin
  - langium
  - libcrypt
  - libxcrypt
  - nixos
  - nixpkgs
  - oxalica
  - pkgs
  - pyproject
  - renovaterc
  - shellformat
  - styl
  - stylintrc
  - tombi
  - trunkio
  - wasi
