name = "Lang"
grammar = "lang"
path_suffixes = ["lang"]
line_comments = ["# "]
brackets = [
  { start = "{", end = "}", close = true, newline = true },
  { start = "[", end = "]", close = true, newline = true },
  { start = "(", end = ")", close = true, newline = true },
  { start = "\"", end = "\"", close = true, newline = false },
]
