lang_file                     ::= [{whitespace | newline}] | [statement {whitespace}] | statement {whitespace} { newline [statement] }

letter                        ::= 'A' | 'B' | 'C' | 'D' | 'E' | 'F' | 'G' | 'H' | 'I' | 'J' | 'K' | 'L' | 'M' | 'N' | 'O' | 'P' | 'Q' | 'R' | 'S' | 'T' | 'U' | 'V' | 'W' | 'X' | 'Y' | 'Z' | 'a' | 'b' | 'c' | 'd' | 'e' | 'f' | 'g' | 'h' | 'i' | 'j' | 'k' | 'l' | 'm' | 'n' | 'o' | 'p' | 'q' | 'r' | 's' | 't' | 'u' | 'v' | 'w' | 'x' | 'y' | 'z'

digit                         ::= '0' | '1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9'

number                        ::= digit { digit }

char                          ::= digit|letter|' '|'!'|'"'|'#'|'$'|'%'|'&'|'\''|'('|')'|'*'|'+'|','|'-'|'.'|'/'|':'|';'|'<'|'='|'>'|'?'|'@'|'['|'\\'|']'|'^'|'_'|'`'|'{'|'|'|'}'|'~'

string                        ::= '\"' { char } '\"'

identifier                    ::= letter { letter | digit | '_' } | '("' [identifier] '")'

parenthesized                 ::= '(' [parenthesized_contest] ')'

parenthesized_contest         ::= list

operator_add                  ::= ' + '

operator_subtract             ::= ' - '

operator_multiply             ::= ' * '

operator_divide               ::= ' / '

operator_power                ::= ' ^ '

operator_concat               ::= ' <> '

operator                      ::= operator_add | operator_subtract | operator_multiply | operator_divide | operator_power | operator_concat

list                          ::= element { ', ' element } | list ', ' more_elements ', ' list

element                       ::= number | string | identifier | expression | equation | parenthesized

where                         ::= 'where'

of_operator                   ::= 'of'

from_operator                 ::= 'from'

more_elements                 ::= '...'

expression                    ::= list { operator list }

whitespace                    ::= ' ' | '\t'

newline                       ::= '\n' | '\r\n'

comment                       ::= '#' { '#' } [ whitespace { char } ]

statement                     ::= comment | equation

equation                      ::= expression comparison expression { comparison expression } {whitespace} [whitespace comment]

comparison_equal_for_each     ::= ' => '

comparison_eaqual             ::= ' = '

comparison_not_equal          ::= ' != '

comparison_more_than          ::= ' > '

comparison_less_than          ::= ' < '

comparison_more_than_or_equal ::= ' >= '

comparison_less_than_or_equal ::= ' <= '

comparison                    ::= comparison_eaqual | comparison_not_equal | comparison_more_than | comparison_less_than | comparison_more_than_or_equal | comparison_less_than_or_equal | comparison_equal_for_each | of_operator | from_operator

function                      ::= identifier parenthesized
