import { type LangiumCoreServices, type Module, type PartialLangiumCoreServices, inject } from 'langium';
import { type DefaultSharedModuleContext, createDefaultModule, createDefaultSharedModule } from 'langium/lsp';
import { LangGeneratedModule, LangGeneratedSharedModule } from './generated/module';
import { LangValidator, registerValidationChecks } from './lang-validator';

/**
 * Declaration of custom services - add your own service classes here.
 */
export type LangAddedServices = {
    validation: {
        LangValidator: LangValidator
    }
};

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of services defined in the `LangAddedServices` interface.
 */
export type LangServices = LangiumCoreServices & LangAddedServices;

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services.
 */
export const LangModule: Module<LangServices, PartialLangiumCoreServices & LangAddedServices> = {
    validation: {
        LangValidator: () => new LangValidator()
    }
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createLangServices(context: DefaultSharedModuleContext) {
    const shared = inject(
        createDefaultSharedModule(context),
        LangGeneratedSharedModule
    );
    const Lang = inject(
        createDefaultModule({ shared }),
        LangGeneratedModule,
        LangModule
    );
    shared.ServiceRegistry.register(Lang);
    registerValidationChecks(Lang);
    return { shared, Lang };
}
